// Package supplychain checks that .github/supply-chain-policy.json still
// describes the pins the workflows actually use.
//
// The file's mechanical fields are generated by tools/supplychainpolicy, so
// these checks are the gate that stops a generated file being left behind by a
// hand-edited workflow — most often a Dependabot bump that moves a SHA and
// nothing else.
//
// Parsing lives in the tool's own package rather than being reimplemented
// here. Two parsers would agree until the day they did not, and the day they
// disagreed is exactly the day this check mattered.
package supplychain

import (
	"strings"
	"testing"

	"github.com/tomlawesome/orbit-launcher/tools/supplychainpolicy/policy"
)

// root is this package's path back to the repository root.
const root = "../.."

func pins(t *testing.T) []policy.Pin {
	t.Helper()
	p, err := policy.CollectPins(root)
	if err != nil {
		t.Fatalf("collecting pins: %v", err)
	}
	return p
}

func load(t *testing.T) policy.Policy {
	t.Helper()
	p, err := policy.Load(root)
	if err != nil {
		t.Fatalf("loading the policy: %v", err)
	}
	return p
}

func TestEveryActionIsPinnedToACommitSHA(t *testing.T) {
	for _, p := range pins(t) {
		if !policy.IsSHA(p.Ref) {
			t.Errorf("%s:%d: %s is pinned to %q, which is not a 40-character commit SHA.\n"+
				"A tag can be moved by whoever owns it; a SHA cannot.",
				p.File, p.Line, p.Full, p.Ref)
		}
	}
}

func TestEveryPinCarriesItsVersionComment(t *testing.T) {
	for _, p := range pins(t) {
		if p.Comment == "" {
			t.Errorf("%s:%d: %s has no `# vX.Y.Z` comment beside its SHA.\n"+
				"Without it a reviewer cannot tell what the hash is without resolving it by hand.",
				p.File, p.Line, p.Full)
		}
	}
}

func TestPolicyMatchesTheWorkflows(t *testing.T) {
	pol := load(t)
	recorded := map[string]policy.Action{}
	for _, a := range pol.Actions {
		recorded[a.Name] = a
	}
	excepted := map[string]bool{}
	for _, e := range pol.Exceptions {
		excepted[e.Name] = true
	}

	const regenerate = "\nRegenerate the policy: go run ./tools/supplychainpolicy -write"

	for _, p := range pins(t) {
		if excepted[p.Action] {
			continue
		}
		a, ok := recorded[p.Action]
		if !ok {
			t.Errorf("%s:%d: %s is used in CI but not recorded in the policy.%s",
				p.File, p.Line, p.Action, regenerate)
			continue
		}
		if a.Commit != p.Ref {
			t.Errorf("%s:%d: %s is pinned to %s but the policy records %s.\n"+
				"One of the two is stale; the workflow is what actually runs.%s",
				p.File, p.Line, p.Action, p.Ref, a.Commit, regenerate)
		}
		if p.Comment != "" && a.Version != p.Comment {
			t.Errorf("%s:%d: %s says %q beside the pin but the policy records version %q.\n"+
				"A comment that disagrees with the record is worse than no comment.%s",
				p.File, p.Line, p.Action, p.Comment, a.Version, regenerate)
		}
	}
}

func TestPolicyRecordsNothingTheWorkflowsNoLongerUse(t *testing.T) {
	pol := load(t)
	used := map[string]bool{}
	for _, p := range pins(t) {
		used[p.Action] = true
	}
	var orphans []string
	for _, a := range pol.Actions {
		if !used[a.Name] {
			orphans = append(orphans, a.Name)
		}
	}
	if len(orphans) > 0 {
		t.Errorf("the policy records actions no workflow uses: %s.\n"+
			"Stale entries make the file look more thorough than it is.\n"+
			"Regenerate the policy: go run ./tools/supplychainpolicy -write",
			strings.Join(orphans, ", "))
	}
}

// TestGeneratedFieldsAreUpToDate is the "generated file is current" gate: the
// mechanical fields must be exactly what the generator would derive today.
// The checks above catch a policy that contradicts a workflow; this catches
// one that has simply drifted out of order or shape.
func TestGeneratedFieldsAreUpToDate(t *testing.T) {
	pol := load(t)
	want := policy.DerivedActions(pins(t))

	if len(pol.Actions) != len(want) {
		t.Fatalf("the policy records %d actions, the workflows pin %d.\n"+
			"Regenerate the policy: go run ./tools/supplychainpolicy -write",
			len(pol.Actions), len(want))
	}
	for i, w := range want {
		got := pol.Actions[i]
		if got.Name != w.Name || got.Commit != w.Commit || got.Version != w.Version {
			t.Errorf("policy entry %d is %s %s %s; the workflows say %s %s %s.\n"+
				"Regenerate the policy: go run ./tools/supplychainpolicy -write",
				i, got.Name, got.Version, got.Commit, w.Name, w.Version, w.Commit)
		}
	}
}

func TestEveryEntryRecordsLicenceAndOwner(t *testing.T) {
	pol := load(t)
	for _, a := range pol.Actions {
		if a.License == "" {
			t.Errorf("action %s records no licence.", a.Name)
		}
		if a.UpdateOwner == "" {
			t.Errorf("action %s records no update owner; an unowned pin is nobody's job.", a.Name)
		}
	}
	for _, tl := range pol.Tools {
		if tl.License == "" {
			t.Errorf("tool %s records no licence.", tl.Name)
		}
		if tl.UpdateOwner == "" {
			t.Errorf("tool %s records no update owner.", tl.Name)
		}
	}
	for _, e := range pol.Exceptions {
		if strings.TrimSpace(e.Reason) == "" {
			t.Errorf("exception %s records no reason; an unexplained exception is just an absence.", e.Name)
		}
	}
}

// TestPinnedToolMatchesTheWorkflow covers the one supply-chain pin that is not
// an action: gitleaks is fetched and checksum-verified inside the job, so its
// version and digest live in an env block where no `uses:` check would see
// them drift.
func TestPinnedToolMatchesTheWorkflow(t *testing.T) {
	pol := load(t)
	var gl *policy.Tool
	for i := range pol.Tools {
		if pol.Tools[i].Name == "gitleaks" {
			gl = &pol.Tools[i]
		}
	}
	if gl == nil {
		t.Fatal("the policy records no gitleaks entry, but secret-scan.yml pins one")
	}

	version, sha256, err := policy.GitleaksPin(root)
	if err != nil {
		t.Fatalf("reading the gitleaks pin: %v", err)
	}
	if version != gl.Version {
		t.Errorf("secret-scan.yml pins gitleaks %s but the policy records %s.", version, gl.Version)
	}
	if sha256 != gl.SHA256 {
		t.Errorf("secret-scan.yml pins gitleaks digest %s but the policy records %s.", sha256, gl.SHA256)
	}
}
