package review

import (
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"
)

// fakeModule writes files (slash paths relative to the module root) into
// a fresh directory and returns it.
func fakeModule(t *testing.T, files map[string]string) string {
	t.Helper()
	root := t.TempDir()
	for name, body := range files {
		p := filepath.Join(root, filepath.FromSlash(name))
		if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(p, []byte(body), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	return root
}

func pkg(root, mod, rel string, goFiles []string, embeds ...string) Package {
	return Package{
		ImportPath: mod + "/" + rel,
		Dir:        filepath.Join(root, filepath.FromSlash(rel)),
		GoFiles:    goFiles,
		EmbedFiles: embeds,
		Module:     &Module{Path: mod, Version: "v1.2.3", Dir: root},
	}
}

const plain = "// Copyright 2024 Example Authors. MIT licence, see LICENSE.\n\npackage p\n\nfunc F() {}\n"

func scan(t *testing.T, pkgs ...Package) []Finding {
	t.Helper()
	got, err := Scan(pkgs)
	if err != nil {
		t.Fatalf("Scan: %v", err)
	}
	return got
}

func TestScan_PlainPackageNeedsNoReview(t *testing.T) {
	root := fakeModule(t, map[string]string{"LICENSE": "MIT", "p.go": plain})
	if got := scan(t, pkg(root, "example.com/m", ".", []string{"p.go"})); len(got) != 0 {
		t.Fatalf("plain package: got %v, want nothing", got)
	}
}

func TestScan_EmbeddedFileNeedsReview(t *testing.T) {
	root := fakeModule(t, map[string]string{"LICENSE": "MIT", "ui/ui.go": plain, "ui/static/logo.png": "png"})
	got := scan(t, pkg(root, "example.com/m", "ui", []string{"ui.go"}, "static/logo.png"))
	want := []Finding{{Module: "example.com/m@v1.2.3", Path: "ui/static/logo.png", Kind: Embed}}
	if !reflect.DeepEqual(got, want) {
		t.Fatalf("got %v, want %v", got, want)
	}
}

func TestScan_ThirdPartyDirectoryIsVendored(t *testing.T) {
	for _, dir := range []string{"third_party/lz", "internal/vendor/lz"} {
		root := fakeModule(t, map[string]string{"LICENSE": "MIT", dir + "/lz.go": plain})
		got := scan(t, pkg(root, "example.com/m", dir, []string{"lz.go"}))
		want := []Finding{{Module: "example.com/m@v1.2.3", Path: dir + "/lz.go", Kind: Vendored}}
		if !reflect.DeepEqual(got, want) {
			t.Errorf("%s: got %v, want %v", dir, got, want)
		}
	}
}

// A licence file below the module root is someone else's code, even with
// no third_party in its path -- including in a parent of the package.
func TestScan_NestedLicenceFileIsVendored(t *testing.T) {
	root := fakeModule(t, map[string]string{
		"LICENSE":               "MIT",
		"internal/xxh/COPYING":  "GPL",
		"internal/xxh/sub/x.go": plain,
		"internal/own/o.go":     plain,
	})
	got := scan(t,
		pkg(root, "example.com/m", "internal/xxh/sub", []string{"x.go"}),
		pkg(root, "example.com/m", "internal/own", []string{"o.go"}),
	)
	want := []Finding{{Module: "example.com/m@v1.2.3", Path: "internal/xxh/sub/x.go", Kind: Vendored}}
	if !reflect.DeepEqual(got, want) {
		t.Fatalf("got %v, want %v", got, want)
	}
}

func TestScan_GeneratedFileNeedsReview(t *testing.T) {
	root := fakeModule(t, map[string]string{
		"LICENSE":  "MIT",
		"tab.go":   "// Code generated by gen.go. DO NOT EDIT.\n\n// Taken from unicode.org.\npackage p\n",
		"after.go": "package p\n\n// Code generated by nothing. DO NOT EDIT.\n",
	})
	got := scan(t, pkg(root, "example.com/m", ".", []string{"after.go", "tab.go"}))
	// tab.go is generated, not also a notice; after.go's marker comes
	// after the package clause, where the convention does not put it.
	want := []Finding{{Module: "example.com/m@v1.2.3", Path: "tab.go", Kind: Generated}}
	if !reflect.DeepEqual(got, want) {
		t.Fatalf("got %v, want %v", got, want)
	}
}

func TestScan_ProvenanceCommentNeedsReview(t *testing.T) {
	fires := []string{
		"// Note: this is mostly ported from tmux/colour.c.",
		"// The information below is extracted and adapted from bits/sysmacros.h",
		"// copied from x/term@v0.1.3.",
		"// Under MIT License",
		"// Licensed under the Apache License, Version 2.0",
		"// SPDX-License-Identifier: GPL-2.0-only",
		"// See https://www.unicode.org/license.html for the Unicode",
		"/* Taken from Foot keymap.h */",
		"/*\n * Borrowed from musl.\n */",
		"x := 1 // translated from the C original",
	}
	for _, c := range fires {
		root := fakeModule(t, map[string]string{"LICENSE": "MIT", "f.go": "package p\n\n" + c + "\n"})
		got := scan(t, pkg(root, "example.com/m", ".", []string{"f.go"}))
		if len(got) != 1 || got[0].Kind != Notice {
			t.Errorf("%q: got %v, want one notice", c, got)
		}
	}
	quiet := []string{
		"// WithContext returns a new Group and an associated Context derived from ctx.",
		"// The licence is in LICENSE.",
		`s := "ported from" // a string, not a comment`,
	}
	for _, c := range quiet {
		root := fakeModule(t, map[string]string{"LICENSE": "MIT", "f.go": "package p\n\n" + c + "\n"})
		if got := scan(t, pkg(root, "example.com/m", ".", []string{"f.go"})); len(got) != 0 {
			t.Errorf("%q: got %v, want nothing", c, got)
		}
	}
}

// Assembly is linked like Go code, and go-licenses cannot inspect it.
func TestScan_AssemblyIsRead(t *testing.T) {
	root := fakeModule(t, map[string]string{"LICENSE": "MIT", "p.go": plain, "asm_amd64.s": "// Adapted from OpenSSL's x86_64 routine.\nTEXT ·f(SB),0,$0\n"})
	p := pkg(root, "example.com/m", ".", []string{"p.go"})
	p.SFiles = []string{"asm_amd64.s"}
	got := scan(t, p)
	if len(got) != 1 || got[0].Path != "asm_amd64.s" || got[0].Kind != Notice {
		t.Fatalf("got %v, want one notice on asm_amd64.s", got)
	}
}

func TestScan_MainModuleIsNotReviewed(t *testing.T) {
	root := fakeModule(t, map[string]string{"third_party/x.go": plain})
	p := pkg(root, "example.com/m", "third_party", []string{"x.go"}, "logo.png")
	p.Module.Main = true
	if got := scan(t, p); len(got) != 0 {
		t.Fatalf("main module: got %v, want nothing", got)
	}
}

func TestScan_OneFindingPerFileAcrossPlatforms(t *testing.T) {
	root := fakeModule(t, map[string]string{"LICENSE": "MIT", "tab.go": "// Code generated by g. DO NOT EDIT.\n\npackage p\n"})
	p := pkg(root, "example.com/m", ".", []string{"tab.go"})
	if got := scan(t, p, p); len(got) != 1 {
		t.Fatalf("same package listed twice (two platforms): got %v, want one finding", got)
	}
}

func mustParse(t *testing.T, text string) []Review {
	t.Helper()
	r, err := ParseReviews(text)
	if err != nil {
		t.Fatalf("ParseReviews: %v", err)
	}
	return r
}

func TestCheck(t *testing.T) {
	findings := []Finding{
		{Module: "example.com/a@v1.0.0", Path: "tab.go", Kind: Generated},
		{Module: "example.com/b@v2.0.0", Path: "unix/z1.go", Kind: Generated},
		{Module: "example.com/b@v2.0.0", Path: "unix/z2.go", Kind: Generated},
		{Module: "example.com/b@v2.0.0", Path: "dev.go", Kind: Notice},
	}

	t.Run("all reviewed", func(t *testing.T) {
		reviews := mustParse(t, `
# comment
example.com/a@v1.0.0 tab.go generated Unicode-3.0
example.com/b@v2.0.0 unix/ generated BSD-3-Clause
example.com/b@v2.0.0 ./ notice BSD-3-Clause
`)
		unreviewed, stale := Check(findings, reviews)
		if len(unreviewed) != 0 || len(stale) != 0 {
			t.Fatalf("unreviewed %v, stale %v; want neither", unreviewed, stale)
		}
	})

	t.Run("unreviewed fails", func(t *testing.T) {
		unreviewed, _ := Check(findings, mustParse(t, "example.com/b@v2.0.0 unix/ generated BSD-3-Clause\n"))
		if len(unreviewed) != 2 {
			t.Fatalf("unreviewed = %v, want tab.go and dev.go", unreviewed)
		}
	})

	t.Run("a review matching nothing is stale", func(t *testing.T) {
		reviews := mustParse(t, `
example.com/a@v1.0.0 tab.go generated Unicode-3.0
example.com/b@v2.0.0 unix/ generated BSD-3-Clause
example.com/b@v2.0.0 dev.go notice BSD-3-Clause
example.com/gone@v1.0.0 x.go notice MIT
`)
		_, stale := Check(findings, reviews)
		if len(stale) != 1 || stale[0].Module != "example.com/gone@v1.0.0" || stale[0].Line != 5 {
			t.Fatalf("stale = %+v, want the gone module's review on line 5", stale)
		}
	})

	t.Run("a version bump re-triggers the review", func(t *testing.T) {
		bumped := []Finding{{Module: "example.com/a@v1.0.1", Path: "tab.go", Kind: Generated}}
		unreviewed, stale := Check(bumped, mustParse(t, "example.com/a@v1.0.0 tab.go generated Unicode-3.0\n"))
		if len(unreviewed) != 1 || len(stale) != 1 {
			t.Fatalf("unreviewed %v, stale %v; want the bumped file unreviewed and the old review stale", unreviewed, stale)
		}
	})

	t.Run("a review covers only its own kind", func(t *testing.T) {
		unreviewed, stale := Check(findings[3:], mustParse(t, "example.com/b@v2.0.0 dev.go generated BSD-3-Clause\n"))
		if len(unreviewed) != 1 || len(stale) != 1 {
			t.Fatalf("unreviewed %v, stale %v; want a kind mismatch to cover nothing", unreviewed, stale)
		}
	})
}

func TestParseReviews_RejectsMalformedLines(t *testing.T) {
	for _, line := range []string{
		"example.com/a tab.go generated MIT",               // no version
		"example.com/a@v1 tab.go generated",                // no licence
		"example.com/a@v1 tab.go copied MIT",               // unknown kind
		"example.com/a@v1 tab.go generated MIT and Apache", // licence with spaces
	} {
		if _, err := ParseReviews(line); err == nil {
			t.Errorf("%q: parsed, want an error", line)
		} else if !strings.Contains(err.Error(), "line 1") {
			t.Errorf("%q: error %q does not name the line", line, err)
		}
	}
}
