// Command supplychainpolicy regenerates or checks
// .github/supply-chain-policy.json.
//
//	go run ./tools/supplychainpolicy            # offline check, as CI runs it
//	go run ./tools/supplychainpolicy -write     # regenerate (needs the network)
//
// Writing reaches the GitHub API for each action's licence, and confirms the
// pinned SHA really is the tag its comment claims. Checking does neither: it
// compares the committed file against what the workflows say, which needs no
// network and so cannot fail for reasons unrelated to the pins.
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"io"
	"net/http"
	"os"
	"strings"
	"time"

	scp "github.com/tomlawesome/orbit-launcher/tools/supplychainpolicy/policy"
)

const defaultOwner = "orbit-launcher maintainers"

var fileComment = []string{
	"Generated by tools/supplychainpolicy — do not edit the mechanical fields by hand.",
	"Regenerate with: go run ./tools/supplychainpolicy -write",
	"",
	"Records what each third-party pin actually is: the version its SHA corresponds to,",
	"its licence, and who owns updating it. `updateOwner` and `note` are human-authored",
	"and are carried across a regeneration; everything else is derived from the workflows.",
	"",
	"There is deliberately no review date. A date could only be moved by hand, and for an",
	"action that simply has not released it went stale while nothing was wrong. Currency is",
	"driven by Dependabot opening a bump, and by test/supplychain refusing a bump that leaves",
	"this file behind.",
}

func main() {
	write := flag.Bool("write", false, "regenerate the policy file (requires network access)")
	root := flag.String("root", ".", "repository root")
	flag.Parse()

	if err := run(*root, *write); err != nil {
		fmt.Fprintf(os.Stderr, "supplychainpolicy: %v\n", err)
		os.Exit(1)
	}
}

func run(root string, write bool) error {
	pins, err := scp.CollectPins(root)
	if err != nil {
		return err
	}
	if write {
		return regenerate(root, pins)
	}
	return check(root, pins)
}

// check is the offline gate. It reports the same drift the test does, but as a
// command a person can run and act on.
func check(root string, pins []scp.Pin) error {
	pol, err := scp.Load(root)
	if err != nil {
		return err
	}
	recorded := map[string]scp.Action{}
	for _, a := range pol.Actions {
		recorded[a.Name] = a
	}
	var problems []string
	for _, p := range pins {
		if !scp.IsSHA(p.Ref) {
			problems = append(problems, fmt.Sprintf("%s:%d %s is pinned to %q, not a commit SHA", p.File, p.Line, p.Full, p.Ref))
			continue
		}
		a, ok := recorded[p.Action]
		if !ok {
			problems = append(problems, fmt.Sprintf("%s:%d %s is not recorded in the policy", p.File, p.Line, p.Action))
			continue
		}
		if a.Commit != p.Ref {
			problems = append(problems, fmt.Sprintf("%s:%d %s pins %s, policy records %s", p.File, p.Line, p.Action, p.Ref, a.Commit))
		}
		if p.Comment != "" && a.Version != p.Comment {
			problems = append(problems, fmt.Sprintf("%s:%d %s comment says %s, policy records %s", p.File, p.Line, p.Action, p.Comment, a.Version))
		}
	}
	if len(problems) > 0 {
		return fmt.Errorf("the policy no longer matches the workflows:\n  %s\n\nRegenerate it:\n  go run ./tools/supplychainpolicy -write",
			strings.Join(problems, "\n  "))
	}
	fmt.Println("supply-chain policy matches the workflows")
	return nil
}

func regenerate(root string, pins []scp.Pin) error {
	previous, _ := scp.Load(root) // absent or older schema is fine; nothing to carry over
	carriedAction := map[string]scp.Action{}
	for _, a := range previous.Actions {
		carriedAction[a.Name] = a
	}

	actions := scp.DerivedActions(pins)
	for i := range actions {
		a := &actions[i]
		if !scp.IsSHA(a.Commit) {
			return fmt.Errorf("%s is pinned to %q, not a commit SHA; fix the workflow before regenerating", a.Name, a.Commit)
		}
		if a.Version == "" {
			return fmt.Errorf("%s has no `# vX.Y.Z` comment beside its pin; add one so the version is recorded", a.Name)
		}
		lic, err := license(a.Name)
		if err != nil {
			return err
		}
		resolved, err := tagCommit(a.Name, a.Version)
		if err != nil {
			return err
		}
		if resolved != a.Commit {
			return fmt.Errorf("%s claims %s beside its pin, but that tag resolves to %s, not the pinned %s",
				a.Name, a.Version, resolved, a.Commit)
		}
		a.License = lic
		a.Source = fmt.Sprintf("https://github.com/%s/releases/tag/%s", a.Name, a.Version)
		a.UpdateOwner = defaultOwner
		if prev, ok := carriedAction[a.Name]; ok {
			if prev.UpdateOwner != "" {
				a.UpdateOwner = prev.UpdateOwner
			}
			a.Note = prev.Note
		}
	}

	glVersion, glSHA, err := scp.GitleaksPin(root)
	if err != nil {
		return err
	}
	glLicense, err := license("gitleaks/gitleaks")
	if err != nil {
		return err
	}
	gl := scp.Tool{
		Name: "gitleaks", Version: glVersion,
		Artifact: fmt.Sprintf("gitleaks_%s_linux_x64.tar.gz", glVersion),
		SHA256:   glSHA, License: glLicense,
		Source:      fmt.Sprintf("https://github.com/gitleaks/gitleaks/releases/tag/v%s", glVersion),
		UsedBy:      ".github/workflows/secret-scan.yml",
		UpdateOwner: defaultOwner,
		Note: "Downloaded and checksum-verified at job time, not an action. " +
			"gitleaks/gitleaks-action is deliberately not used: it reports NOASSERTION and is " +
			"commercially licensed for organisations.",
	}
	for _, prev := range previous.Tools {
		if prev.Name == "gitleaks" {
			if prev.UpdateOwner != "" {
				gl.UpdateOwner = prev.UpdateOwner
			}
			if prev.Note != "" {
				gl.Note = prev.Note
			}
		}
	}

	out := scp.Policy{
		SchemaVersion: scp.SchemaVersion,
		Comment:       fileComment,
		Actions:       actions,
		Tools:         []scp.Tool{gl},
		Exceptions:    previous.Exceptions,
	}
	if out.Exceptions == nil {
		out.Exceptions = []scp.Exception{}
	}
	body, err := scp.Marshal(out)
	if err != nil {
		return err
	}
	if err := os.WriteFile(scp.PolicyPath, body, 0o644); err != nil {
		return fmt.Errorf("writing the policy: %w", err)
	}
	fmt.Printf("wrote %s: %d actions, %d tools\n", scp.PolicyPath, len(out.Actions), len(out.Tools))
	return nil
}

var client = &http.Client{Timeout: 20 * time.Second}

func api(path string, into any) error {
	req, err := http.NewRequest(http.MethodGet, "https://api.github.com"+path, nil)
	if err != nil {
		return err
	}
	req.Header.Set("Accept", "application/vnd.github+json")
	if tok := os.Getenv("GITHUB_TOKEN"); tok != "" {
		req.Header.Set("Authorization", "Bearer "+tok)
	}
	resp, err := client.Do(req)
	if err != nil {
		return fmt.Errorf("GET %s: %w", path, err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		snippet, _ := io.ReadAll(io.LimitReader(resp.Body, 200))
		return fmt.Errorf("GET %s: %s: %s", path, resp.Status, strings.TrimSpace(string(snippet)))
	}
	return json.NewDecoder(resp.Body).Decode(into)
}

func license(repo string) (string, error) {
	var r struct {
		License struct {
			SPDX string `json:"spdx_id"`
		} `json:"license"`
	}
	if err := api("/repos/"+repo, &r); err != nil {
		return "", err
	}
	if r.License.SPDX == "" || r.License.SPDX == "NOASSERTION" {
		return "", fmt.Errorf("%s reports licence %q; record it deliberately rather than generating it",
			repo, r.License.SPDX)
	}
	return r.License.SPDX, nil
}

// tagCommit resolves a tag to the commit it points at, dereferencing an
// annotated tag object. Pinning to a tag object rather than a commit gives no
// protection, so this is what confirms the comment beside a pin is true.
func tagCommit(repo, tag string) (string, error) {
	var ref struct {
		Object struct {
			SHA  string `json:"sha"`
			Type string `json:"type"`
		} `json:"object"`
	}
	if err := api(fmt.Sprintf("/repos/%s/git/ref/tags/%s", repo, tag), &ref); err != nil {
		return "", err
	}
	if ref.Object.Type != "tag" {
		return ref.Object.SHA, nil
	}
	var annotated struct {
		Object struct {
			SHA string `json:"sha"`
		} `json:"object"`
	}
	if err := api(fmt.Sprintf("/repos/%s/git/tags/%s", repo, ref.Object.SHA), &annotated); err != nil {
		return "", err
	}
	return annotated.Object.SHA, nil
}
