package main

import (
	"bytes"
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/tomlawesome/orbit-launcher/tools/licencereview/review"
)

// shipped stands in for review.Shipped: one dependency, example.com/m
// v1.0.0, carrying a generated table and an embedded logo.
func shipped(t *testing.T) func() ([]review.Package, error) {
	t.Helper()
	root := t.TempDir()
	write(t, filepath.Join(root, "LICENSE"), "MIT")
	write(t, filepath.Join(root, "tab.go"), "// Code generated by gen. DO NOT EDIT.\n\npackage m\n")
	write(t, filepath.Join(root, "logo.png"), "png")
	pkgs := []review.Package{{
		ImportPath: "example.com/m",
		Dir:        root,
		GoFiles:    []string{"tab.go"},
		EmbedFiles: []string{"logo.png"},
		Module:     &review.Module{Path: "example.com/m", Version: "v1.0.0", Dir: root},
	}}
	return func() ([]review.Package, error) { return pkgs, nil }
}

func write(t *testing.T, name, body string) string {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(name), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(name, []byte(body), 0o644); err != nil {
		t.Fatal(err)
	}
	return name
}

const allReviewed = `# reviews
example.com/m@v1.0.0 logo.png embed MIT
example.com/m@v1.0.0 tab.go generated MIT
`

// licencereview runs the command as `go run ./tools/licencereview args...`
// would, and returns its exit code and output.
func licencereview(t *testing.T, lister func() ([]review.Package, error), args ...string) (code int, stdout, stderr string) {
	t.Helper()
	var out, errOut bytes.Buffer
	code = cli(append([]string{"licencereview"}, args...), &out, &errOut, lister)
	return code, out.String(), errOut.String()
}

func TestCLI_AllReviewedPasses(t *testing.T) {
	reviews := write(t, filepath.Join(t.TempDir(), "r.txt"), allReviewed)
	code, stdout, stderr := licencereview(t, shipped(t), "-review", reviews)
	if code != 0 || stdout != "2 findings, all reviewed\n" || stderr != "" {
		t.Fatalf("exit %d, stdout %q, stderr %q; want 0 and the all-reviewed line", code, stdout, stderr)
	}
}

// With no -review, the command reads .github/licence-review.txt from the
// directory it runs in: the module root, as CI runs it.
func TestCLI_ReadsTheRepoReviewFileByDefault(t *testing.T) {
	dir := t.TempDir()
	write(t, filepath.Join(dir, ".github", "licence-review.txt"), allReviewed)
	t.Chdir(dir)
	if code, stdout, stderr := licencereview(t, shipped(t)); code != 0 {
		t.Fatalf("exit %d, stdout %q, stderr %q; want 0", code, stdout, stderr)
	}
}

func TestCLI_UnreviewedFindingFails(t *testing.T) {
	reviews := write(t, filepath.Join(t.TempDir(), "r.txt"), "example.com/m@v1.0.0 logo.png embed MIT\n")
	code, stdout, stderr := licencereview(t, shipped(t), "-review", reviews)
	if code != 1 {
		t.Fatalf("exit %d, want 1", code)
	}
	if stdout != "unreviewed: example.com/m@v1.0.0 tab.go generated\n" {
		t.Errorf("stdout = %q, want just the unreviewed table", stdout)
	}
	if !strings.Contains(stderr, "1 unreviewed, 0 stale") || !strings.Contains(stderr, "owner") {
		t.Errorf("stderr = %q, want the count and whose decision a licence is", stderr)
	}
}

// A review left behind after a version bump, or after a module goes,
// fails too, naming its file and line so it can be deleted.
func TestCLI_StaleReviewFails(t *testing.T) {
	reviews := write(t, filepath.Join(t.TempDir(), "r.txt"), allReviewed+"example.com/m@v0.9.0 tab.go generated MIT\n")
	code, stdout, stderr := licencereview(t, shipped(t), "-review", reviews)
	if code != 1 {
		t.Fatalf("exit %d, want 1", code)
	}
	want := "stale: " + reviews + ":4 example.com/m@v0.9.0 tab.go generated matches nothing linked"
	if !strings.HasPrefix(stdout, want) || strings.Contains(stdout, "unreviewed") {
		t.Errorf("stdout = %q, want only %q...", stdout, want)
	}
	if !strings.Contains(stderr, "0 unreviewed, 1 stale") {
		t.Errorf("stderr = %q, want the counts", stderr)
	}
}

// -list prints every finding and passes without reading the review file,
// so it works before the file has an entry for a new dependency.
func TestCLI_ListPrintsEveryFindingWithoutReviews(t *testing.T) {
	code, stdout, stderr := licencereview(t, shipped(t), "-list", "-review", filepath.Join(t.TempDir(), "absent.txt"))
	want := "example.com/m@v1.0.0 logo.png embed\nexample.com/m@v1.0.0 tab.go generated\n"
	if code != 0 || stdout != want || stderr != "" {
		t.Fatalf("exit %d, stdout %q, stderr %q; want 0 and %q", code, stdout, stderr, want)
	}
}

// Anything that stops the check from finishing fails it, with the
// reason on stderr: a check that cannot run must not pass.
func TestCLI_FailsClosed(t *testing.T) {
	dir := t.TempDir()
	malformed := write(t, filepath.Join(dir, "bad.txt"), "example.com/m tab.go generated MIT\n")
	unreadable := func() ([]review.Package, error) {
		return []review.Package{{ImportPath: "example.com/m", Dir: dir, GoFiles: []string{"gone.go"}, Module: &review.Module{Path: "example.com/m", Version: "v1.0.0", Dir: dir}}}, nil
	}
	cases := []struct {
		name   string
		lister func() ([]review.Package, error)
		args   []string
		want   string
	}{
		{"go list fails", func() ([]review.Package, error) { return nil, errors.New("go list for linux/amd64: boom") }, nil, "boom"},
		{"a linked file cannot be read", unreadable, nil, "gone.go"},
		{"no review file", shipped(t), []string{"-review", filepath.Join(dir, "absent.txt")}, "absent.txt"},
		{"malformed review file", shipped(t), []string{"-review", malformed}, malformed + ": line 1"},
	}
	for _, c := range cases {
		code, stdout, stderr := licencereview(t, c.lister, c.args...)
		if code != 1 || !strings.HasPrefix(stderr, "licencereview: ") || !strings.Contains(stderr, c.want) {
			t.Errorf("%s: exit %d, stdout %q, stderr %q; want 1 and an error naming %q", c.name, code, stdout, stderr, c.want)
		}
	}
}

// Flags behave as Go's default flag set's do: a bad one is a usage error
// (exit 2) that never runs the check, and -h prints usage and exits 0.
func TestCLI_FlagErrorsAndHelp(t *testing.T) {
	ran := false
	lister := func() ([]review.Package, error) { ran = true; return nil, nil }

	code, _, stderr := licencereview(t, lister, "-bogus")
	if code != 2 || !strings.Contains(stderr, "-bogus") || !strings.Contains(stderr, "Usage of licencereview") {
		t.Errorf("bad flag: exit %d, stderr %q; want 2 and usage", code, stderr)
	}
	code, _, stderr = licencereview(t, lister, "-h")
	if code != 0 || !strings.Contains(stderr, "-list") {
		t.Errorf("-h: exit %d, stderr %q; want 0 and usage", code, stderr)
	}
	if ran {
		t.Error("the check ran despite a flag error or -h")
	}
}
