// Package notices builds the third-party notices the launcher carries
// (#182): every linked module's own licence files, the Go distribution's
// licence (the standard library and runtime are linked into every
// binary), and the hand-kept notices in internal/notices/extra for code a
// module carries from elsewhere (#176's findings) that its own licence
// file does not name.
package notices

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"github.com/tomlawesome/orbit-launcher/tools/licencereview/review"
)

// licenceFile matches the file names go-licenses itself treats as
// licences.
var licenceFile = regexp.MustCompile(`(?i)^(licen[cs]e|copying|notice|unlicense)(\.(txt|md|markdown|rst))?$`)

// Extra is one hand-kept notice: Text applies to the code Modules carry
// from elsewhere.
type Extra struct {
	Name    string
	Modules []string
	About   string
	Text    string
}

// ParseExtra reads one file from internal/notices/extra: "Module: <path>"
// lines (one or more), one "About: <what>" line, a blank line, then the
// notice text.
func ParseExtra(name, content string) (Extra, error) {
	head, text, ok := strings.Cut(content, "\n\n")
	if !ok {
		return Extra{}, fmt.Errorf("%s: no blank line after the header", name)
	}
	e := Extra{Name: name, Text: strings.TrimSpace(text)}
	for _, line := range strings.Split(head, "\n") {
		key, value, ok := strings.Cut(line, ": ")
		switch {
		case ok && key == "Module":
			e.Modules = append(e.Modules, value)
		case ok && key == "About":
			e.About = value
		default:
			return Extra{}, fmt.Errorf("%s: header line %q is not \"Module: <path>\" or \"About: <what>\"", name, line)
		}
	}
	if len(e.Modules) == 0 || e.About == "" || e.Text == "" {
		return Extra{}, fmt.Errorf("%s: needs at least one Module line, an About line and a notice", name)
	}
	return e, nil
}

// Build returns the notices file for pkgs. goLicence is the text of the
// Go distribution's LICENSE. It fails if a linked module has no licence
// file at its root, or an extra names a module nothing links.
func Build(pkgs []review.Package, goLicence string, extras []Extra) (string, error) {
	mods := map[string]*review.Module{}
	for _, p := range pkgs {
		if p.Module != nil && !p.Module.Main {
			mods[p.Module.Path] = p.Module
		}
	}
	paths := make([]string, 0, len(mods))
	for path := range mods {
		paths = append(paths, path)
	}
	sort.Strings(paths)

	var b strings.Builder
	b.WriteString(`Third-party notices for orbit-launcher

orbit-launcher is licensed under AGPL-3.0. It is built from the code
below, whose licences ask for these notices to go with every copy.

Generated by tools/licencenotices from the modules linked into the
shipped binary (linux/amd64, linux/arm64). Do not edit by hand.
`)
	section := func(title, text string) {
		fmt.Fprintf(&b, "\n\n==== %s ====\n\n%s\n", title, strings.TrimSpace(text))
	}
	section("Go standard library and runtime (LICENSE)", goLicence)

	for _, path := range paths {
		m := mods[path]
		entries, err := os.ReadDir(m.Dir)
		if err != nil {
			return "", err
		}
		found := false
		for _, e := range entries {
			if e.IsDir() || !licenceFile.MatchString(e.Name()) {
				continue
			}
			text, err := os.ReadFile(filepath.Join(m.Dir, e.Name()))
			if err != nil {
				return "", err
			}
			section(fmt.Sprintf("%s %s (%s)", m.Path, m.Version, e.Name()), string(text))
			found = true
		}
		if !found {
			return "", fmt.Errorf("%s %s has no licence file at its root; its notice cannot be shipped", m.Path, m.Version)
		}
	}

	sort.Slice(extras, func(i, j int) bool { return extras[i].Name < extras[j].Name })
	for _, e := range extras {
		for _, path := range e.Modules {
			if mods[path] == nil {
				return "", fmt.Errorf("%s names %s, which the launcher no longer links; delete or update it", e.Name, path)
			}
		}
		section(fmt.Sprintf("Carried by %s: %s", strings.Join(e.Modules, ", "), e.About), e.Text)
	}
	return b.String(), nil
}
