// Package notices holds the third-party licence notices the launcher
// carries and prints with --licences (#182). THIRD_PARTY_NOTICES.txt is
// generated by tools/licencenotices; CI fails when it falls behind the
// modules the binary links.
package notices

import _ "embed"

// Text is every notice the shipped binary owes, as one plain-text
// document.
//
//go:embed THIRD_PARTY_NOTICES.txt
var Text string
